#!/usr/bin/env bash
# Rebuild the page images from the source PDF.
#   ./build.sh path/to/portfolio.pdf
# Requires: poppler (pdftoppm), webp (cwebp), python3 with Pillow.
#   brew install poppler webp && pip3 install pillow
set -euo pipefail

PDF="${1:?usage: ./build.sh path/to/portfolio.pdf}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "→ rendering pages at 300 dpi"
pdftoppm -png -r 300 "$PDF" "$WORK/p"

echo "→ deriving webp tiers"
mkdir -p "$ROOT/pages/full" "$ROOT/pages/view" "$ROOT/pages/thumb"
WORK="$WORK" ROOT="$ROOT" python3 - <<'PY'
from PIL import Image
import glob, os, subprocess, json

work, root = os.environ["WORK"], os.environ["ROOT"]
# tier, target width in px, webp quality
TIERS = [("full", 2600, 88),   # click-to-zoom detail (~300 dpi native)
         ("view", 1400, 88),   # what the spread shows
         ("thumb", 320, 80)]   # index grid + blur-up placeholder

masters = sorted(glob.glob(f"{work}/p-*.png"))
first = Image.open(masters[0])
for f in masters:
    n = int(os.path.basename(f).split("-")[1].split(".")[0])
    im = Image.open(f).convert("RGB")
    for tier, w, q in TIERS:
        tmp = f"{work}/_scaled.png"
        im.resize((w, round(im.height * w / im.width)), Image.LANCZOS).save(tmp)
        subprocess.run(["cwebp", "-q", str(q), "-m", "6", "-sharp_yuv",
                        "-metadata", "none", tmp, "-o", f"{root}/pages/{tier}/{n:02d}.webp"],
                       check=True, capture_output=True)
    print(f"  page {n:02d}", flush=True)

aspect = round(first.width / first.height, 6)
json.dump({"pages": len(masters), "aspect": aspect},
          open(f"{root}/pages/manifest.json", "w"), indent=2)
full_w = dict((t[0], t[1]) for t in TIERS)["full"]
open(f"{root}/assets/book.js", "w").write(
    "/* generated by build.sh — do not edit by hand */\n"
    "window.BOOK = {\n"
    f"  pages: {len(masters)},\n"
    f"  aspect: {aspect},   /* page width / height */\n"
    f"  fullWidth: {full_w}     /* px width of the zoom tier */\n"
    "};\n")

card = Image.new("RGB", (1200, 630), (14, 14, 14))
cov = Image.open(masters[0]).convert("RGB")
h = 520; w = round(cov.width * h / cov.height)
card.paste(cov.resize((w, h), Image.LANCZOS), ((1200 - w) // 2, (630 - h) // 2))
card.save(f"{root}/pages/social.jpg", quality=88, optimize=True)
PY

echo "→ done"
du -sh "$ROOT/pages"
