#!/usr/bin/env bash
# Render a PDF into the page tiers one book needs.
#   ./build.sh path/to/book.pdf <book-dir>
# e.g. ./build.sh "~/portfolio.pdf" photography
#
# Handles both export shapes:
#   portrait pages  -> paired as cover, 2-3, 4-5 ... last alone
#   landscape 2-ups -> already spreads; split into leaves, paired 1-2, 3-4 ...
#
# Requires: poppler (pdftoppm), webp (cwebp), python3 with Pillow.
#   brew install poppler webp && pip3 install pillow
set -euo pipefail

PDF="${1:?usage: ./build.sh path/to/book.pdf <book-dir>}"
BOOK="${2:?usage: ./build.sh path/to/book.pdf <book-dir>}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
DEST="$ROOT/$BOOK"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

FULL_W=2600   # px per leaf in the zoom tier; the master renders straight to it

read -r PTS_W PTS_H < <(pdfinfo "$PDF" | awk '/^Page size:/ {print $3, $5}')
LEAVES=$(python3 -c "print(2 if $PTS_W/$PTS_H > 1.3 else 1)")
echo "→ ${PTS_W}x${PTS_H} pts, $LEAVES leaf/leaves per page"

echo "→ rendering masters at $((FULL_W * LEAVES)) px wide"
pdftoppm -png -scale-to-x $((FULL_W * LEAVES)) -scale-to-y -1 "$PDF" "$WORK/m"

mkdir -p "$DEST/pages/full" "$DEST/pages/view" "$DEST/pages/thumb"
WORK="$WORK" DEST="$DEST" LEAVES="$LEAVES" FULL_W="$FULL_W" python3 - <<'PY'
from PIL import Image
import glob, os, subprocess, json

work, dest = os.environ["WORK"], os.environ["DEST"]
leaves, full_w = int(os.environ["LEAVES"]), int(os.environ["FULL_W"])
TIERS = [("full", full_w, 88),   # click-to-zoom detail
         ("view", 1400, 88),     # what the spread shows
         ("thumb", 320, 80)]     # index grid + blur-up placeholder

masters = sorted(glob.glob(f"{work}/m-*.png"))

# a landscape export is already a spread: cut it back into leaves so the
# viewer can pair them itself, and so narrow screens get one page at a time
pages = []
for f in masters:
    im = Image.open(f).convert("RGB")
    if leaves == 2:
        half = im.width // 2
        pages += [im.crop((0, 0, half, im.height)), im.crop((half, 0, im.width, im.height))]
    else:
        pages.append(im)

for n, im in enumerate(pages, 1):
    for tier, w, q in TIERS:
        tmp = f"{work}/_scaled.png"
        (im if im.width == w else im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)).save(tmp)
        subprocess.run(["cwebp", "-q", str(q), "-m", "6", "-sharp_yuv",
                        "-metadata", "none", tmp, "-o", f"{dest}/pages/{tier}/{n:02d}.webp"],
                       check=True, capture_output=True)
    print(f"  page {n:02d}", flush=True)

first = pages[0]
aspect = round(first.width / first.height, 6)
pairing = "spreads" if leaves == 2 else "cover"
open(f"{dest}/book.js", "w").write(
    "/* generated by build.sh — do not edit by hand */\n"
    "window.BOOK = {\n"
    f"  pages: {len(pages)},\n"
    f"  aspect: {aspect},   /* leaf width / height */\n"
    f"  fullWidth: {full_w},     /* px width of the zoom tier */\n"
    f'  pairing: "{pairing}"   /* "cover": 1, 2-3 ... N alone | "spreads": 1-2, 3-4 ... */\n'
    "};\n")

card = Image.new("RGB", (1200, 630), (14, 14, 14))
cov = pages[0] if leaves == 1 else Image.open(masters[0]).convert("RGB")
h = 520; w = round(cov.width * h / cov.height)
if w > 1160: w, h = 1160, round(cov.height * 1160 / cov.width)
card.paste(cov.resize((w, h), Image.LANCZOS), ((1200 - w) // 2, (630 - h) // 2))
card.save(f"{dest}/pages/social.jpg", quality=88, optimize=True)
print(f"→ {len(pages)} leaves, aspect {aspect}, pairing {pairing}")
PY

du -sh "$DEST/pages"
