#!/usr/bin/env bash
# Render a PDF into the page tiers a document needs.
#   ./build.sh path/to/book.pdf <dir>
# e.g. ./build.sh "~/portfolio.pdf" photography
#      ./build.sh "~/cv.pdf" cv
#
# Books (photography, work) get three lossy tiers and handle both export shapes:
#   portrait pages  -> paired as cover, 2-3, 4-5 ... last alone
#   landscape 2-ups -> already spreads; split into leaves, paired 1-2, 3-4 ...
#
# The cv takes its own path: one lossless tier. For type, lossless is crisper
# and smaller than lossy. No zoom or index, so no other tier is needed.
#
# Requires: poppler (pdftoppm), webp (cwebp), python3 with Pillow.
#   brew install poppler webp && pip3 install pillow
set -euo pipefail

PDF="${1:?usage: ./build.sh path/to/document.pdf <dir>}"
BOOK="${2:?usage: ./build.sh path/to/document.pdf <dir>}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
DEST="$ROOT/$BOOK"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# ── the cv: one lossless tier, plus the pdf itself for download ──────────────
if [ "$BOOK" = "cv" ]; then
  CV_W=2000
  echo "→ cv: rendering at ${CV_W}px wide, lossless"
  mkdir -p "$DEST/pages"
  rm -f "$DEST/pages"/*.webp
  pdftoppm -png -scale-to-x "$CV_W" -scale-to-y -1 "$PDF" "$WORK/p"
  n=0
  for f in "$WORK"/p-*.png; do
    n=$((n + 1))
    cwebp -quiet -lossless -m 6 -metadata none "$f" -o "$DEST/pages/$n.webp"
    echo "  page $n"
  done
  cp "$PDF" "$DEST/Vo_Kenny_CV.pdf"
  echo "→ copied the pdf itself for the download link"

  # page count and links come from the pdf, so pages.js needs no hand editing.
  # aspect reads from the pdf page box: this Pillow has no webp decoder.
  read -r CV_PTS_W CV_PTS_H < <(pdfinfo "$PDF" | awk '/^Page size:/ {print $3, $5}')
  PYTHONPATH="$ROOT" DEST="$DEST" PDF="$PDF" PAGES="$n" \
    PTS_W="$CV_PTS_W" PTS_H="$CV_PTS_H" python3 - <<'CVPY'
import json, os

dest, pdf, pages = os.environ["DEST"], os.environ["PDF"], int(os.environ["PAGES"])
aspect = round(float(os.environ["PTS_W"]) / float(os.environ["PTS_H"]), 6)

links = {}
try:
    import linkmap
    links = linkmap.extract(pdf, 1)
    print(f"→ carried over {linkmap.count(links)} hyperlink(s)")
except ImportError:
    print("⚠  pypdf not installed — hyperlinks NOT carried over (pip3 install pypdf)")

open(f"{dest}/pages.js", "w").write(
    "/* generated by build.sh — do not edit by hand */\n"
    "window.CV = {\n"
    f"  pages: {pages},\n"
    f"  aspect: {aspect},   /* page width / height */\n"
    "  /* link rects, as fractions of a page */\n"
    f"  links: {json.dumps(links, indent=2)}\n"
    "};\n")
CVPY
  du -sh "$DEST/pages"
  exit 0
fi

FULL_W=2600   # px per leaf in the zoom tier; the master renders straight to it

read -r PTS_W PTS_H < <(pdfinfo "$PDF" | awk '/^Page size:/ {print $3, $5}')
LEAVES=$(python3 -c "print(2 if $PTS_W/$PTS_H > 1.3 else 1)")
echo "→ ${PTS_W}x${PTS_H} pts, $LEAVES leaf/leaves per page"

echo "→ rendering masters at $((FULL_W * LEAVES)) px wide"
pdftoppm -png -scale-to-x $((FULL_W * LEAVES)) -scale-to-y -1 "$PDF" "$WORK/m"

mkdir -p "$DEST/pages/full" "$DEST/pages/view" "$DEST/pages/thumb"
PYTHONPATH="$ROOT" WORK="$WORK" DEST="$DEST" LEAVES="$LEAVES" FULL_W="$FULL_W" PDF="$PDF" python3 - <<'PY'
from PIL import Image
import glob, os, subprocess, json

work, dest = os.environ["WORK"], os.environ["DEST"]
leaves, full_w = int(os.environ["LEAVES"]), int(os.environ["FULL_W"])
TIERS = [("full", full_w, 88),   # click-to-zoom
         ("view", 1400, 88),     # spread
         ("thumb", 320, 80)]     # index grid, blur-up placeholder

masters = sorted(glob.glob(f"{work}/m-*.png"))

# landscape exports are already spreads; split into leaves so the viewer can
# pair them and narrow screens can show one page at a time
pages = []
for f in masters:
    im = Image.open(f).convert("RGB")
    if leaves == 2:
        half = im.width // 2
        pages += [im.crop((0, 0, half, im.height)), im.crop((half, 0, im.width, im.height))]
    else:
        pages.append(im)

for n, im in enumerate(pages, 1):
    for tier, w, q in TIERS:
        tmp = f"{work}/_scaled.png"
        (im if im.width == w else im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)).save(tmp)
        subprocess.run(["cwebp", "-q", str(q), "-m", "6", "-sharp_yuv",
                        "-metadata", "none", tmp, "-o", f"{dest}/pages/{tier}/{n:02d}.webp"],
                       check=True, capture_output=True)
    print(f"  page {n:02d}", flush=True)

# ── live hyperlinks ────────────────────────────────────────────────
links = {}
try:
    import linkmap
    links = linkmap.extract(os.environ["PDF"], leaves)
    print(f"→ carried over {linkmap.count(links)} hyperlink(s)")
except ImportError:
    print("⚠  pypdf not installed — hyperlinks NOT carried over (pip3 install pypdf)")

first = pages[0]
aspect = round(first.width / first.height, 6)
pairing = "spreads" if leaves == 2 else "cover"
open(f"{dest}/book.js", "w").write(
    "/* generated by build.sh — do not edit by hand */\n"
    "window.BOOK = {\n"
    f"  pages: {len(pages)},\n"
    f"  aspect: {aspect},   /* leaf width / height */\n"
    f"  fullWidth: {full_w},     /* px width of the zoom tier */\n"
    f'  pairing: "{pairing}",   /* "cover": 1, 2-3 ... N alone | "spreads": 1-2, 3-4 ... */\n'
    "  /* link rects, as fractions of a leaf */\n"
    f"  links: {json.dumps(links, indent=2)}\n"
    "};\n")

card = Image.new("RGB", (1200, 630), (14, 14, 14))
cov = pages[0] if leaves == 1 else Image.open(masters[0]).convert("RGB")
h = 520; w = round(cov.width * h / cov.height)
if w > 1160: w, h = 1160, round(cov.height * 1160 / cov.width)
card.paste(cov.resize((w, h), Image.LANCZOS), ((1200 - w) // 2, (630 - h) // 2))
card.save(f"{dest}/pages/social.jpg", quality=88, optimize=True)
print(f"→ {len(pages)} leaves, aspect {aspect}, pairing {pairing}")
PY

du -sh "$DEST/pages"
