/* generated by build.sh; do not edit by hand */
window.CV = {
  pages: 2,
  aspect: 0.772727,   /* page width / height */
  /* link rects, as fractions of a page */
  links: {
  "1": [
    {
      "x": 0.11595,
      "y": 0.12857,
      "w": 0.17459,
      "h": 0.01594,
      "href": "https://www.linkedin.com/in/kenny-t-vo/",
      "chip": "pages/link/1-0.webp"
    },
    {
      "x": 0.47095,
      "y": 0.12857,
      "w": 0.17459,
      "h": 0.01594,
      "href": "https://kenny-t-vo.github.io/",
      "chip": "pages/link/1-1.webp"
    },
    {
      "x": 0.30445,
      "y": 0.12857,
      "w": 0.15259,
      "h": 0.01594,
      "href": "mailto:kenny.t.vo@outlook.com",
      "chip": "pages/link/1-2.webp"
    }
  ]
}
};
