/* generated by build.sh — do not edit by hand */
window.CV = {
  pages: 2,
  aspect: 0.772727,   /* page width / height */
  /* link rects, as fractions of a page */
  links: {
  "1": [
    {
      "x": 0.11326,
      "y": 0.12854,
      "w": 0.18247,
      "h": 0.03299,
      "href": "https://www.linkedin.com/in/kenny-t-vo/",
      "chip": "pages/link/1-0.webp"
    },
    {
      "x": 0.30326,
      "y": 0.12854,
      "w": 0.15947,
      "h": 0.03299,
      "href": "mailto:kenny.t.vo@outlook.com",
      "chip": "pages/link/1-1.webp"
    },
    {
      "x": 0.46976,
      "y": 0.12854,
      "w": 0.18447,
      "h": 0.03299,
      "href": "https://kenny-t-vo.github.io/",
      "chip": "pages/link/1-2.webp"
    }
  ]
}
};
