/* generated by build.sh — do not edit by hand */
window.CV = {
  pages: 2,
  aspect: 0.772727,   /* page width / height */
  /* live links lifted from the pdf, as fractions of a page */
  links: {
  "1": [
    {
      "x": 0.11397,
      "y": 0.13545,
      "w": 0.18088,
      "h": 0.02639,
      "href": "https://www.linkedin.com/in/kenny-t-vo/"
    },
    {
      "x": 0.30302,
      "y": 0.13545,
      "w": 0.15876,
      "h": 0.02639,
      "href": "mailto:kenny.t.vo@outlook.com"
    },
    {
      "x": 0.46995,
      "y": 0.13545,
      "w": 0.1832,
      "h": 0.02639,
      "href": "https://kenny-t-vo.github.io/"
    }
  ]
}
};
