/* generated by build.sh — do not edit by hand */
window.BOOK = {
  pages: 32,
  aspect: 0.77266,   /* leaf width / height */
  fullWidth: 2600,     /* px width of the zoom tier */
  pairing: "cover"   /* "cover": 1, 2-3 ... N alone | "spreads": 1-2, 3-4 ... */
};
